export const UNIVERSITIES = [
  "Abilene Christian University",
  "Alvin Community College",
  "Amarillo College",
  "Amberton University",
  "Angelina College",
  "Angelo State University",
  "Arlington Baptist University",
  "Austin College",
  "Austin Community College",
  "Baylor University",
  "Blinn College",
  "Brazosport College",
  "Central Texas College",
  "Cisco College",
  "Clarendon College",
  "Coastal Bend College",
  "College of the Mainland Community College District",
  "Collin College",
  "Concordia University Texas",
  "Dallas Baptist University",
  "Dallas College",
  "Del Mar College",
  "East Texas A&M University",
  "East Texas Baptist University",
  "El Paso Community College District",
  "Frank Phillips College",
  "Galveston College",
  "Grayson College",
  "Hardin-Simmons University",
  "Hill College",
  "Houston Christian University",
  "Houston Community Colleges",
  "Howard College",
  "Howard Payne University",
  "Huston-Tillotson University",
  "Jacksonville College",
  "Jarvis Christian College",
  "Kilgore College",
  "Lamar Institute of Technology",
  "Lamar State College at Orange",
  "Lamar State College at Port Arthur",
  "Lamar University",
  "Laredo College",
  "Lee College",
  "LeTourneau University",
  "Lone Star College System",
  "Lubbock Christian University",
  "McLennan Community College",
  "McMurry University",
  "Midland College",
  "Midwestern State University",
  "Navarro College",
  "Nelson University",
  "North Central Texas College",
  "Northeast Lakeview College",
  "Northeast Texas Community College",
  "Northwest Vista College",
  "Odessa College",
  "Our Lady of the Lake University",
  "Palo Alto College",
  "Panola College",
  "Paris Junior College",
  "Parker University",
  "Paul Quinn College",
  "Prairie View A&M University",
  "Ranger College",
  "Rice University",
  "Sam Houston State University",
  "San Antonio College",
  "San Jacinto College North Campus",
  "Schreiner University",
  "South Plains College",
  "South Texas College",
  "Southern Methodist University",
  "SouthWest College For the Deaf",
  "Southwest Texas Junior College",
  "Southwestern Adventist University",
  "Southwestern Christian College",
  "Southwestern University",
  "St. Edward's University",
  "St. Mary's University",
  "St. Philip's College",
  "Stephen F. Austin State University",
  "Sul Ross State University",
  "Sul Ross State University Rio Grande College",
  "Tarleton State University",
  "Tarrant County College-Northwest Campus",
  "Temple College",
  "Texarkana College",
  "Texas A&M International University",
  "Texas A&M University",
  "Texas A&M University at Galveston",
  "Texas A&M University-Central Texas",
  "Texas A&M University-Corpus Christi",
  "Texas A&M University-Kingsville",
  "Texas A&M University-San Antonio",
  "Texas A&M University-Texarkana",
  "Texas Christian University",
  "Texas College",
  "Texas Lutheran University",
  "Texas Southern University",
  "Texas Southmost College",
  "Texas State Technical Colleges",
  "Texas State University",
  "Texas Tech University",
  "Texas Wesleyan University",
  "Texas Woman's University",
  "Trinity University",
  "Trinity Valley Community College",
  "Tyler Junior College",
  "University of Dallas",
  "University of Houston",
  "University of Houston-Clear Lake",
  "University of Houston-Downtown",
  "University of Houston-Victoria",
  "University of Mary Hardin-Baylor",
  "University of North Texas",
  "University of North Texas at Dallas",
  "University of St. Thomas",
  "University of Texas - Rio Grande Valley",
  "University of Texas at Arlington",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Texas at El Paso",
  "University of Texas at San Antonio",
  "University of Texas at Tyler",
  "University of Texas Permian Basin",
  "University of The Incarnate Word",
  "Vernon College",
  "Victoria College",
  "Wayland Baptist University",
  "Weatherford College",
  "West Texas A&M University",
  "Western Texas College",
  "Wharton County Junior College",
  "Wiley College"
];

export const MAJORS = [
  "Accounting",
  "Aerospace Engineering",
  "African American Studies",
  "Agricultural Economics",
  "Agriculture",
  "American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Architecture",
  "Art",
  "Art History",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Communication Studies",
  "Computer Engineering",
  "Computer Science",
  "Criminal Justice",
  "Dance",
  "Drama/Theatre",
  "Earth Science",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Science",
  "Environmental Studies",
  "Film Studies",
  "Finance",
  "Foreign Languages",
  "Geography",
  "Geology",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Hospitality Management",
  "Human Development",
  "Industrial Engineering",
  "Information Systems",
  "International Relations",
  "Journalism",
  "Kinesiology",
  "Liberal Arts",
  "Linguistics",
  "Management",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Music",
  "Neuroscience",
  "Nursing",
  "Nutrition",
  "Petroleum Engineering",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Public Relations",
  "Real Estate",
  "Religious Studies",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Spanish",
  "Statistics",
  "Supply Chain Management",
  "Undecided",
  "Urban Planning",
  "Women's Studies"
];
